### ISSUE TITLE
Hello，can you tell me how to run this project?

### ISSUE THREAD

**Issue by BCWang93** [amanwalia92/TORCS-GAIL#1]
Hello,I am very interested in this project,can you tell me how can I run this code?Thank you very much!

**Comment by amanwalia123** [comment]
1. Clone the repository using `git clone https://github.com/amanwalia92/TORCS-GAIL.git`
2. `cd <basedir>/TORCS-GAIL/Deterministic-GAIL/`
3. `python test.py`
